### ISSUE TITLE
Support signature verification

### ISSUE THREAD

**Issue by kylef** [kylef/JSONWebToken.swift#3]

**Comment by fesor** [comment]
I found this confusing for developers to set `verify` to true by default. Since this library mostly used on the client side, it will be better to make signature verification skipped by default.

The reason is that when developers trying to use your library they start to think that they need to verify signature of token on their side. This leads to possible security issue since they need secret key on the client side. Only authorization server should know secret key, otherwise we can easily compromise all or our authentication system.

p.s. true story, one of iOS developers asked me to give him secret key.
