### ISSUE TITLE
decoding fails for a JWT generated with java library

### ISSUE THREAD

**Issue by pratikdas** [kylef/JSONWebToken.swift#36]
The decoding of below jwt token is failing with an error: Invalid algorithm. I have used HS256 as the algorithm and my signing secret is 'pratik'. Issuer is blank. I am using version 1.4.0 since I am running with swift 2.0.

eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJpZDEiLCJpYXQiOjE0NjUyNTgzODcsInN1YiI6InN1YmplY3QxIn0.up3EiW_4feVcgfBvVEiPiVDiAZLeMnRRfu6sqLne3E0

**Comment by kylef** [comment]
The key does not actually seem to be `pratik` for this JWT. I've tried to validate this with jwt.io and the Python JWT library and they all say it's not valid. I think the problem lies on the encoding side here.

![screen shot 2016-06-06 at 18 45 10](https://cloud.githubusercontent.com/assets/44164/15843451/1b86acc2-2c17-11e6-908a-2e1d801842fc.png)

```shell
$ python
>>> import jwt
>>> jwt.decode('eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJpZDEiLCJpYXQiOjE0NjUyNTgzODcsInN1YiI6InN1YmplY3QxIn0.up3EiW_4feVcgfBvVEiPiVDiAZLeMnRRfu6sqLne3E0', 'pratik', algorithms=['HS256'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kyle/Projects/tmp/venv/lib/python2.7/site-packages/jwt/api_jwt.py", line 64, in decode
    options, **kwargs)
  File "/Users/kyle/Projects/tmp/venv/lib/python2.7/site-packages/jwt/api_jws.py", line 115, in decode
    key, algorithms)
  File "/Users/kyle/Projects/tmp/venv/lib/python2.7/site-packages/jwt/api_jws.py", line 178, in _verify_signature
    raise DecodeError('Signature verification failed')
jwt.exceptions.DecodeError: Signature verification failed
```
