### ISSUE TITLE
Swift packager install fails

### ISSUE THREAD

**Issue by CocoaPriest** [kylef/JSONWebToken.swift#63]
`error: rename error: Directory not empty (66): /Users/x/dev/p/server/Packages/CryptoSwift.git -> /Users/x/dev/p/server/Packages/CryptoSwift-0.6.7`

**Comment by Joannis** [comment]
@CocoaPriest @kylef The issue here is with MongoKitten and other projects that rely on CryptoSwift. [This line of code](https://github.com/kylef/JSONWebToken.swift/blob/master/Package.swift#L6) doesn't contain the `.git` suffix that everyone uses.

[Unlike here](https://github.com/OpenKitten/MongoKitten/blob/mongokitten4/Package.swift#L19) and [here](https://github.com/kylef/Stencil/blob/master/Package.swift#L9).

A PR is really straightforward and unnecessary, it's adding 4 characters. @kylef could you fix this?
